# Generated by Django 4.1.4 on 2022-12-10 23:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría del CV',
                'verbose_name_plural': 'Categorías del CV',
                'db_table': 'category_CV',
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('held_position', models.CharField(max_length=300, verbose_name='Cargo ocupado')),
                ('functions', ckeditor.fields.RichTextField(verbose_name='Funciones')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Voluntariado',
                'verbose_name_plural': 'Voluntariados',
                'db_table': 'volunteering',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duración')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'training',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Apellidos y Nombres')),
                ('held_position', models.CharField(max_length=300, verbose_name='Cargo ocupado')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('phone', models.CharField(max_length=13, verbose_name='Teléfono')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='Pre_Professional_Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('held_position', models.CharField(max_length=300, verbose_name='Cargo ocupado')),
                ('functions', ckeditor.fields.RichTextField(verbose_name='Funciones')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Práctica Pre Profesional',
                'verbose_name_plural': 'Prácticas Pre Profesionales',
                'db_table': 'pre_professional_practice',
            },
        ),
        migrations.CreateModel(
            name='Other_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('image', models.ImageField(default='null', upload_to='photos_other_data', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Otro Dato',
                'verbose_name_plural': 'Otros Datos',
                'db_table': 'other_data',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=200, verbose_name='Entidad')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('level', models.CharField(blank=True, max_length=200, verbose_name='Nivel')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('held_position', models.CharField(max_length=300, verbose_name='Cargo ocupado')),
                ('functions', ckeditor.fields.RichTextField(verbose_name='Funciones')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='Nivel')),
                ('note', models.CharField(blank=True, max_length=20, verbose_name='Nota')),
                ('image', models.ImageField(default='null', upload_to='photos_education', verbose_name='Imagen')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duración')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=200, verbose_name='Entidad')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de finalización')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duración')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Congreso',
                'verbose_name_plural': 'Congresos',
                'db_table': 'congress',
            },
        ),
        migrations.CreateModel(
            name='Computers_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(blank=True, max_length=200, verbose_name='Entidad')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('framework', models.CharField(blank=True, max_length=400, verbose_name='Entorno de trabajo')),
                ('level', models.CharField(blank=True, max_length=200, verbose_name='Nivel')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Habilidad informática',
                'verbose_name_plural': 'Habilidades informáticas',
                'db_table': 'computers_skill',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('image', models.ImageField(default='null', upload_to='photos_achievement', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAcercaDe.category_cv', verbose_name='Categoría del CV')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'achievement',
            },
        ),
    ]
