# Generated by Django 4.1.4 on 2022-12-11 00:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('repository_address', models.CharField(max_length=100, verbose_name='Dirección del repositorio')),
                ('image', models.ImageField(default='null', upload_to='photos_briefcase', verbose_name='Imagen')),
                ('public', models.BooleanField(verbose_name='¿Publicado?')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': 'briefcase',
            },
        ),
    ]
